global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  # Monitor Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Node Exporter (system metrics)
  - job_name: node-exporter
    static_configs:
      - targets: ['localhost:9100']

  # Monitor Nginx availability via Blackbox Exporter
  - job_name: nginx-probe
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://localhost/     # This is your Nginx homepage
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # Blackbox Exporter

